import Appbar from "@/components/Layout/Appbar";
import Footer from "@/components/Layout/Footer";
import ThemeRegistry from "@/theme/ThemeRegistry";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "ScanSight",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeRegistry>
        <body>
          <Appbar />
          {children}
          <Footer />
        </body>
      </ThemeRegistry>
    </html>
  );
}
